# 프로덕션 환경 설정
# 사용법: java -jar app.jar --spring.profiles.active=prod
# 또는: SPRING_PROFILES_ACTIVE=prod java -jar app.jar

spring:
  # 데이터베이스 연결 설정 (프로덕션 - 환경변수 필수)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME} # 환경변수 필수
    password: ${DB_PASSWORD} # 환경변수 필수
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50 # 프로덕션 트래픽 처리
      minimum-idle: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1 # 커넥션 유효성 검사

  # JPA 설정 (프로덕션)
  jpa:
    hibernate:
      ddl-auto: validate # 프로덕션에서는 validate만 (Flyway 사용)
    show-sql: false # SQL 로깅 비활성화
    properties:
      hibernate:
        generate_statistics: false # 통계 비활성화 (성능 최적화)
        format_sql: false # 포맷팅 비활성화
        cache:
          use_second_level_cache: true # 캐시 활성화
          use_query_cache: true

# 서버 설정
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful # Graceful shutdown 활성화
  error:
    include-message: never # 에러 메시지 숨김
    include-binding-errors: never # 바인딩 에러 숨김
    include-stacktrace: never # 스택트레이스 숨김
    include-exception: false # 예외 정보 숨김

# JWT 설정 (프로덕션 - 환경변수 필수)
jwt:
  secret: ${JWT_SECRET} # 환경변수 필수 (최소 256비트)
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour (보안 강화)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:259200000} # 3 days

# 로깅 설정 (프로덕션 - 최소 레벨)
logging:
  level:
    root: WARN
    com.boilerplate: INFO # 애플리케이션 로그만 INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: ${LOG_PATH:/var/log/springboot}/prod-application.log
    max-size: 100MB
    max-history: 90 # 90일 보관

# Actuator 설정 (프로덕션 - 최소 노출)
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus # 필수 엔드포인트만
  endpoint:
    health:
      show-details: never # 보안을 위해 상세 정보 숨김
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger UI (프로덕션에서는 비활성화 권장)
springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false} # 기본 비활성화
  api-docs:
    enabled: ${API_DOCS_ENABLED:false} # 기본 비활성화

# 보안 관련 설정
security:
  allowed-ips: [] # 허용할 IP 목록 (예: 127.0.0.1, 192.168.0.1). 비어있으면 모든 IP 허용.

# 파일 저장 경로 설정
file:
  upload-dir: ./uploads # 파일이 업로드될 기본 경로
  allowed-extensions: ["jpg", "jpeg", "png", "gif", "pdf", "txt", "zip"] # 허용할 파일 확장자 목록. 비어있으면 모두 허용.
